FROM ros:foxy-ros-core

RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential file clang-format python3-colcon-common-extensions python3-rosdep \
    && rm -rf /var/lib/apt/lists/*

# Create ROS workspace
COPY . /ws/src/imu_tools
WORKDIR /ws

# Use rosdep to install all dependencies (including ROS itself)
RUN rosdep init && rosdep update && apt-get update && rosdep install --from-paths src -i -y --rosdistro foxy \
    && rm -rf /var/lib/apt/lists/*

RUN /bin/bash -c "source /opt/ros/foxy/setup.bash && \
    colcon build --parallel-workers 1 && \
    colcon test --parallel-workers 1"
